language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: '$SONAR_CLOUD_ORG'
    token:
      secure: '$SONAR_CLOUD_TOKEN'
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'